### ISSUE TITLE
Allow placeholders in entry module file name

### ISSUE THREAD

**Issue by peter-at-work** [smapiot/piral-cli-webpack#1]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

piral cli using `piral-cli-webpack` 0.15.0, specifically the `pilet-webpack-plugin` package.

## Description

`pilet-webpack-plugin` uses the _webpack_ _BannerPlugin_ to emit a comment with some metadata info into the entry module (normally _index.js_).

When a pilet build environment customizes the webpack configuration to use a different output filename for the entry module, the BannerPlugin does not emit the metadata into the entry module.

## Steps to Reproduce

1. We have a pilet build environment that overrides (via _webpack.config.js_) the webpack configuration to use a different filename for the entry module
```
  config.output.filename = 'index.[chunkhash:8].js';
```

2. Upon running `pilet build`, the entry module is emitted with the expected filename, but the pilet comment/metadata is absent in the module content itself.  This results in the pilet package (tgz) being treated using the v0 spec instead of the v2 spec.

## Expected behavior

The banner/comment inside the entry module should be present.

## Actual behavior

The banner/comment inside the entry module is missing.

## Possible Origin / Solution

Each instantiation of the BannerPlugin in _packages/pilet-webpack-plugin/src/index.ts_ sets the following plugin configuration:
```
        entryOnly: true,
        include: `${mainEntry}.js`,
```

When webpack configuration is customized, the match process on the _include_ property results in a false match, and the BannerPlugin will not emit the comment.

The _entryOnly_ property (being set to `true`) is enough to indicate that a comment should be emitted in the entry module.  The _include_ property can be removed and makes the plugin usable in more webpack configurations.

**Comment by FlorianRappl** [comment]
Yeah I think that makes sense - mind doing a PR? Thanks!

**Comment by peter-at-work** [comment]
Digging further into this, it seems like the presence/removal of the _include_ property is just part of the solution.  The _include_ was originally needed in order to only add the banner to the main entrypoint/chunk.

Looks like a limitation on webpack's BannerPlugin where the _include/exclude/test_ properties are being evaluated against the output asset filenames.  For pilet development, where the _webpack.config.js_ configuration can be overridden (e.g., output filename format), the _piral-cli-webpack_ package won't know what predetermined regular expression to use for the BannerPlugin.

Within BannerPlugin, as it loops through the output assets, it does have metadata information about the chunks and their configured names (not just the output asset filename), so we may be able to make use of that information to conditionally set the banner for the main entry module.

**Comment by FlorianRappl** [comment]
Yeah that might be one way; the other is that the `piral-cli` already knows what other assets to exclude (the shared deps), so it could hand over this information. Now, using the exclusions and the entry information the decision could be made again without having to rely on the pre-determined output name. Would that be another option in your opinion?
